version: '3'
services:
    apache:
        build: .docker/apache
        container_name: ${DOCKER_APP_NAME}_apache
        labels:
          - "traefik.backend=${DOCKER_APP_NAME}-apache"
          - "traefik.frontend.rule=Host:${DOCKER_APP_NAME}.docker"
          - "traefik.port=80"
        ports:
          - "80"
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/var/www
        depends_on:
          - php
        networks:
          - default

    mysql:
        image: mysql:8
        container_name: ${DOCKER_APP_NAME}_mysql
        labels:
          - "traefik.enable=false"
        volumes:
          - .docker/data/db:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
          - "3306:3306"
        networks:
          - default

    php:
        build: .docker/php
        container_name: ${DOCKER_APP_NAME}_php
        labels:
          - "traefik.enable=false"
        volumes:
          - .:/var/www
          - $HOME/.composer:$HOME/.composer # Share composer cache
        environment:
          - maildev_host=maildev.docker
        depends_on:
          - maildev
          - mysql
        networks:
          - default

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${DOCKER_APP_NAME}_phpmyadmin
        labels:
          - "traefik.backend=${DOCKER_APP_NAME}-phpmyadmin"
          - "traefik.frontend.rule=Host:pma.docker"
          - "traefik.port=80"
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
          PMA_USER: ${MYSQL_USER}
          PMA_PASSWORD: ${MYSQL_PASSWORD}
        ports:
          - "80"
        volumes:
          - /sessions
          - .docker/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php
        depends_on:
          - mysql
        links:
          - mysql
        networks:
          - default

    maildev:
        image: djfarrelly/maildev
        container_name: ${DOCKER_APP_NAME}_maildev
        labels:
          - "traefik.backend=${DOCKER_APP_NAME}-mail"
          - "traefik.frontend.rule=Host:maildev.docker"
          - "traefik.port=80"
          - "traefik.frontend.passHostHeader=true"
        ports:
          - 80
          - "1025:25"
        networks:
          - default

    traefik:
        image: traefik
        command: -c /dev/null --api --docker --docker.domain=.docker --logLevel=DEBUG
        ports:
          - "80:80"
          - "8080:8080"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - default

networks:
  default:
    driver: bridge