version: '3'
services:
    apache:
        build: .docker/apache
        container_name: ${DOCKER_APP_NAME}_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf4
        depends_on:
          - php

    mysql:
        image: mysql
        container_name: ${DOCKER_APP_NAME}_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4

    php:
        build: .docker/php
        container_name: ${DOCKER_APP_NAME}_php
        volumes:
          - .:/home/wwwroot/sf4
        environment:
          - maildev_host=${DOCKER_APP_NAME}_maildev.local
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${DOCKER_APP_NAME}_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: ${DOCKER_APP_NAME}_maildev
        ports:
          - 8001:80
