version: '3'
services:
    apache:
        build: .docker/apache
        container_name: ${DOCKER_APP_NAME}_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/var/www
        depends_on:
          - php

    mysql:
        image: mysql:8
        container_name: ${DOCKER_APP_NAME}_mysql
        volumes:
          - .docker/data/db:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
          - 3306:3306

    php:
        build: .docker/php
        container_name: ${DOCKER_APP_NAME}_php
        volumes:
          - .:/var/www
        environment:
          - maildev_host=sf4.mail
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${DOCKER_APP_NAME}_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
          PMA_USER: ${MYSQL_USER}
          PMA_PASSWORD: ${MYSQL_PASSWORD}
        ports:
          - 8080:80
        volumes:
          - /sessions
          - .docker/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php
        depends_on:
          - mysql
        links:
          - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: ${DOCKER_APP_NAME}_maildev
        ports:
          - 8001:80
          - 1025:25
